const makePracticeQuestion = (id, number, chapter, question, options, answer, explanation) => ({
  id, number, chapter, question, options, answer, explanation
});

window.practiceSets = {
  setA: [
    makePracticeQuestion("A1", 1, 1,
      "Which statement best describes an advantage of a multi-layer communication model?",
      ["Every layer must be redesigned whenever one protocol changes", "A layer can be changed without redesigning every other layer if its interfaces remain stable", "Layering removes all transmission overhead", "All layers use the same protocol", "A layered model guarantees faster communication"],
      1,
      "Layering isolates functions. A protocol or implementation can change inside one layer without forcing changes everywhere else, as long as the layer's interfaces and services remain consistent."),
    makePracticeQuestion("A2", 2, 1,
      "Which statement correctly describes a WAN?",
      ["They are always owned entirely by the organization using them", "They are limited to a single floor", "They can use only wired transmission", "They cannot connect LANs", "They commonly use services or circuits supplied by telecommunications carriers"],
      4,
      "WANs connect networks over large geographic areas and commonly depend on facilities or services supplied by telecommunications carriers."),
    makePracticeQuestion("A3", 3, 1,
      "An intranet is best described as...",
      ["A private network intended for authorized members of an organization", "A network that is available to every Internet user", "A long-distance leased circuit", "A file-transfer protocol", "A network used only for wireless devices"],
      0,
      "An intranet uses network and web technologies for private organizational use, with access limited to authorized internal users."),
    makePracticeQuestion("A4", 4, 1,
      "Communication protocols...",
      ["Must always be implemented as application software", "Are used only on point-to-point circuits", "May be implemented in hardware, software, or both", "Must use IP addressing", "Cannot change after a network is installed"],
      2,
      "A protocol is a set of communication rules. Depending on its function, those rules can be implemented in hardware, software, or a combination."),

    makePracticeQuestion("A5", 5, 2,
      "Which of the following is NOT a transaction-processing system (TPS)?",
      ["Airline reservation system", "Retail point-of-sale system", "Payroll processing system", "Live music streaming service", "Bank deposit system"],
      3,
      "A music streaming service delivers media rather than recording routine business transactions. The other systems process transactions that change organizational records."),
    makePracticeQuestion("A6", 6, 2,
      "Which function is NOT normally part of a transaction-processing application architecture?",
      ["Presentation logic", "Application logic", "CSMA/CD media arbitration", "Data-access logic", "Data storage"],
      2,
      "CSMA/CD is a LAN media-access method. The remaining choices are the standard functional components of an information-system application."),
    makePracticeQuestion("A7", 7, 2,
      "Which layer of the Internet Model does HTTP belong to?",
      ["Physical", "Application", "Data Link", "Network", "Transport"],
      1,
      "HTTP provides web communication services directly to applications, so it belongs to the application layer."),
    makePracticeQuestion("A8", 8, 2,
      "What is a major limitation of client-based architecture?",
      ["Moving large amounts of data to clients can create slow response and excessive network traffic", "The server must perform every presentation task", "Clients cannot contain application logic", "It works only with wireless networks", "It cannot store data on a server"],
      0,
      "Client-based designs may send large datasets across the network for local processing, which can create heavy traffic and poor performance."),
    makePracticeQuestion("A9", 9, 2,
      "Which is a common disadvantage of host-based architecture?",
      ["Central processors perform nearly all processing and may become a bottleneck", "Every client needs a complete database copy", "It cannot be centrally managed", "Applications must run without a server", "It always requires a wireless link"],
      0,
      "A host-based system concentrates work on one host or a small group of processors, creating a possible performance bottleneck."),
    makePracticeQuestion("A10", 10, 2,
      "Which statement best describes Software as a Service (SaaS)?",
      ["The customer manages the application, operating system, and data centre", "Only physical cabling is outsourced", "The customer must install the full application on every client", "The provider operates the application and its supporting software platform", "SaaS is another name for peer-to-peer architecture"],
      3,
      "In SaaS, the provider hosts and operates the application along with the supporting platform; the customer accesses the software as a service."),
    makePracticeQuestion("A11", 11, 2,
      "In client-based architecture, the server is primarily responsible for...",
      ["Data storage", "All presentation logic", "All application logic", "Controlling the physical layer", "Replacing every client operating system"],
      0,
      "Client-based architecture places presentation, application, and data-access work on the client while the server primarily stores data."),
    makePracticeQuestion("A12", 12, 2,
      "Which statement applies to a thin-client architecture?",
      ["Every client stores the complete organizational database", "Clients perform all application and data-access logic", "The system cannot use a server", "The client must manage network routing", "The client may handle only presentation while most processing occurs on a server"],
      4,
      "A thin client performs minimal local work, often limited to the user interface, while the server handles most application and data processing."),

    makePracticeQuestion("A13", 13, 3,
      "What technique is used to reduce interference in twisted-pair cable?",
      ["Increasing the connector size", "Bundling every conductor into one straight line", "Twisting the conductors into pairs", "Removing the cable jacket", "Using only one conductor"],
      2,
      "Twisting each conductor pair helps cancel electromagnetic interference and reduces crosstalk between pairs."),
    makePracticeQuestion("A14", 14, 3,
      "What is a commonly supported maximum distance for long-reach single-mode Ethernet?",
      ["100 m", "40 km", "500 m", "2 km", "10 m"],
      1,
      "Long-reach single-mode Ethernet commonly supports spans of about 40 km with the appropriate optics."),
    makePracticeQuestion("A15", 15, 3,
      "Half-duplex data flow means...",
      ["Communication is possible in one direction only", "Both devices must transmit continuously", "Communication can occur in both directions, but not at the same time", "Both directions always operate simultaneously", "The link runs at half of its advertised data rate"],
      2,
      "Half-duplex supports communication in both directions, but only one side transmits at any given moment."),
    makePracticeQuestion("A16", 16, 3,
      "How many wire pairs are found in a typical twisted-pair Ethernet cable?",
      ["1", "2", "3", "4", "8"],
      3,
      "A standard twisted-pair Ethernet cable contains four pairs, which equals eight individual conductors."),
    makePracticeQuestion("A17", 17, 3,
      "CRC-32 is primarily used to...",
      ["Correct every damaged bit automatically", "Detect errors in transmitted data", "Assign MAC addresses", "Encrypt a frame", "Convert analog signals into digital signals"],
      1,
      "CRC-32 produces an error-checking value that lets a receiver detect corruption; it does not repair the corrupted data."),

    makePracticeQuestion("A18", 18, 4,
      "A class C network must be divided into at least 10 subnets. What is the maximum number of usable hosts on each equal-size subnet?",
      ["62", "32", "16", "14", "10"],
      3,
      "Ten subnets require 4 borrowed bits because 2⁴ = 16. Four host bits remain, producing 2⁴ − 2 = 14 usable hosts per subnet."),
    makePracticeQuestion("A19", 19, 4,
      "An IPv4 subnet uses the mask 255.255.255.248. What is the maximum number of usable hosts on that subnet?",
      ["2", "6", "8", "14", "248"],
      1,
      "255.255.255.248 is /29, leaving 3 host bits. That gives 2³ − 2 = 6 usable host addresses."),
    makePracticeQuestion("A20", 20, 4,
      "Consider a class B network with a subnet mask of 255.255.255.192. What is the maximum number of subnets?",
      ["64", "256", "512", "1024", "4096"],
      3,
      "The /26 mask borrows 10 bits beyond the class B /16 default. Therefore, it provides 2¹⁰ = 1,024 subnets."),
    makePracticeQuestion("A21", 21, 4,
      "A class A network needs at least 9 subnets. How many bits must be borrowed from the host ID?",
      ["2", "3", "4", "8", "9"],
      2,
      "Three bits provide only 8 subnets, so 4 bits are required. Four borrowed bits provide 2⁴ = 16 subnets."),
    makePracticeQuestion("A22", 22, 4,
      "A segment is the name commonly given to the PDU at which Internet Model layer?",
      ["Application", "Physical", "Data Link", "Network", "Transport"],
      4,
      "The transport-layer PDU is commonly called a segment, particularly when discussing TCP."),
    makePracticeQuestion("A23", 23, 4,
      "Which statement about the IPv4 subnet mask 255.255.224.0 is true?",
      ["It is a /16 mask", "Devices on the same subnet share the same 19 leftmost bits", "It leaves 19 host bits in a class C network", "It is an invalid mask because 224 cannot appear in a mask", "Devices must share the same three rightmost bytes"],
      1,
      "255.255.224.0 contains 19 consecutive 1-bits, so it is /19 and the leftmost 19 bits identify the subnet."),
    makePracticeQuestion("A24", 24, 4,
      "A class B network must support at least 20 subnets. What subnet mask results when the minimum number of bits is borrowed?",
      ["255.255.248.0", "255.255.240.0", "255.255.224.0", "255.255.255.0", "255.255.20.0"],
      0,
      "Twenty subnets require 5 borrowed bits because 2⁵ = 32. A class B /16 plus 5 bits gives /21, or 255.255.248.0."),
    makePracticeQuestion("A25", 25, 4,
      "Which Internet protocol stack layers normally run only on end systems rather than on routers?",
      ["Physical and Data Link", "Data Link and Network", "Application and Transport", "Physical and Network", "Network and Transport"],
      2,
      "Routers forward data using the physical, data-link, and network layers. Application and transport processing normally occurs at end systems."),

    makePracticeQuestion("A26", 26, 5,
      "Which three layers form the hierarchical Structured Network Design model?",
      ["Physical, Data Link, Network", "Access, Distribution, Core", "Client, Server, Cloud", "LAN, MAN, WAN", "Application, Transport, Network"],
      1,
      "The structured hierarchical design model is divided into access, distribution, and core layers."),
    makePracticeQuestion("A27", 27, 5,
      "Which devices are most commonly found at the network access layer?",
      ["Mainframes and database servers", "Only WAN routers", "Firewalls and leased lines", "Edge switches and wireless access points", "Satellite transmitters"],
      3,
      "End devices connect to the network through access-layer switches and wireless access points."),
    makePracticeQuestion("A28", 28, 5,
      "Which is the clearest example of a multipoint circuit?",
      ["A dedicated fibre link between two switches", "A leased line between two offices", "A point-to-point WAN circuit", "A direct cable between a PC and a switch", "A local wireless network sharing one radio channel"],
      4,
      "Many wireless devices share the same radio medium, making a WLAN a common multipoint circuit."),
    makePracticeQuestion("A29", 29, 5,
      "Where is twisted-pair Ethernet cabling most commonly used?",
      ["Access-layer connections to end devices", "Transoceanic links", "Long-distance carrier backbones", "Underwater WAN circuits", "Satellite uplinks"],
      0,
      "Twisted-pair Ethernet is designed for relatively short access-layer runs between switches and end devices."),
    makePracticeQuestion("A30", 30, 5,
      "The purpose of “CS” in CSMA/CD is...",
      ["To listen for an active carrier before beginning transmission", "To correct a damaged Ethernet frame", "To select the fastest available cable", "To secure the shared medium", "To split a collision into smaller packets"],
      0,
      "CS means Carrier Sense: a station listens to determine whether the shared medium is busy before transmitting."),
  ],

  setB: [
    makePracticeQuestion("B1", 1, 1,
      "Which statement is true about layered network models?",
      ["A layer provides services to the layer above it", "Every layer must use the same addressing method", "Adding layers always increases transmission speed", "The physical layer contains all application protocols", "A protocol can operate only on one device"],
      0,
      "Each layer performs a defined set of functions and provides services to the layer above it through a known interface."),
    makePracticeQuestion("B2", 2, 1,
      "Which of the following statements about WANs is true?",
      ["A WAN cannot contain wireless links", "A WAN is confined to one building", "A WAN always belongs to one private owner", "A WAN has a maximum range of 100 km", "A WAN may span cities or countries using service-provider infrastructure"],
      4,
      "WANs interconnect locations across large geographic areas and often use telecommunications-provider infrastructure."),
    makePracticeQuestion("B3", 3, 1,
      "An extranet allows...",
      ["Authorized external partners to access selected organizational resources", "Only employees inside one office to access a printer", "Any Internet user to administer the private network", "A router to operate without protocols", "A coaxial cable to carry two signals"],
      0,
      "An extranet gives approved external users, such as business partners or suppliers, controlled access to selected private resources."),
    makePracticeQuestion("B4", 4, 1,
      "A communication protocol normally defines...",
      ["Only the brand of equipment that may be used", "The format, ordering, and handling of exchanged messages", "The geographic size of a network", "Only the transmission cable colour", "The price of a leased circuit"],
      1,
      "Protocols define rules such as message format, sequence, timing, and the actions taken when messages are sent or received."),

    makePracticeQuestion("B5", 5, 2,
      "Which system is NOT primarily a transaction-processing system?",
      ["Hotel booking system", "Warehouse inventory system", "Credit-card payment system", "Internet podcast streaming service", "University registration system"],
      3,
      "Podcast streaming distributes media content; the other systems process business events that update stored records."),
    makePracticeQuestion("B6", 6, 2,
      "Which item is NOT one of the standard functions of a transaction-processing system?",
      ["Presentation logic", "Application logic", "Wireless frequency hopping", "Data-access logic", "Data storage"],
      2,
      "Frequency hopping is a wireless transmission technique, not a functional component of a transaction-processing application."),
    makePracticeQuestion("B7", 7, 2,
      "Which layer of the Internet Model does DNS belong to?",
      ["Physical", "Application", "Data Link", "Network", "Transport"],
      1,
      "DNS provides name-resolution services to applications and therefore belongs to the application layer."),
    makePracticeQuestion("B8", 8, 2,
      "Why can client-based architecture produce excessive network load?",
      ["Large amounts of server data may be transferred to clients for processing", "Clients are prohibited from displaying information", "All data is processed inside network switches", "The server contains no stored data", "It uses simplex communication only"],
      0,
      "When clients perform data-access and application processing, they may request large datasets from the server, increasing network traffic."),
    makePracticeQuestion("B9", 9, 2,
      "Which problem is associated with host-based architecture?",
      ["Failure or overload of the central host can affect many users", "Every workstation must store a separate database", "There is no central management", "It cannot use terminals", "Users must supply their own WAN circuit"],
      0,
      "Because processing is centralized, the host can become both a bottleneck and a critical point whose failure affects many users."),
    makePracticeQuestion("B10", 10, 2,
      "In a typical SaaS arrangement...",
      ["The customer must maintain the provider's servers", "The application cannot be accessed through a browser", "Only the network cable is supplied by the provider", "The provider hosts and maintains the application while the customer uses it as a service", "The customer must write every application update"],
      3,
      "SaaS shifts hosting, maintenance, and updates of the application to the service provider."),
    makePracticeQuestion("B11", 11, 2,
      "Client-based architecture is an arrangement in which...",
      ["The server is mainly responsible for storing shared data", "Every computer is equally a client and server", "The server performs all presentation and application logic", "No data crosses the network", "Only mainframe terminals can be used"],
      0,
      "In the client-based model, clients perform much of the processing while the server mainly stores and supplies shared data."),
    makePracticeQuestion("B12", 12, 2,
      "A thin client typically...",
      ["Stores the full database locally", "Performs all business processing without a server", "Controls routing for the entire organization", "Requires two operating systems", "Handles the user interface while servers perform most other processing"],
      4,
      "Thin clients minimize local processing and depend on servers for most application and data functions."),

    makePracticeQuestion("B13", 13, 3,
      "How does coaxial cable primarily reduce external electromagnetic interference?",
      ["By twisting four pairs together", "By surrounding the centre conductor with a conductive shield", "By removing insulation", "By transmitting only in simplex mode", "By using eight separate connectors"],
      1,
      "The conductive outer shield in coaxial cable protects the central signal conductor from electromagnetic interference."),
    makePracticeQuestion("B14", 14, 3,
      "Which distance is most reasonable as a typical upper range for multimode fibre Ethernet rather than single-mode fibre?",
      ["80 km", "40 km", "10 km", "500 m", "100 km"],
      3,
      "Multimode fibre is commonly used for shorter building or campus links measured in hundreds of metres; 500 m is the matching choice."),
    makePracticeQuestion("B15", 15, 3,
      "Full-duplex data flow means...",
      ["Communication occurs in one direction only", "Devices take turns using the link", "Communication can occur in both directions at the same time", "The data rate is cut in half", "One direction must always be faster"],
      2,
      "Full-duplex permits simultaneous transmission in both directions."),
    makePracticeQuestion("B16", 16, 3,
      "A standard twisted-pair Ethernet cable contains how many pairs of conductors?",
      ["1", "2", "3", "4", "6"],
      3,
      "The cable contains four twisted pairs, or eight individual conductors."),
    makePracticeQuestion("B17", 17, 3,
      "Which statement about CRC-32 is correct?",
      ["It guarantees correction of every error", "It is an error-detection method", "It assigns an IP address", "It is a transport protocol", "It encrypts application data"],
      1,
      "CRC-32 checks whether a block of received bits is likely to have been corrupted, but it does not correct the error."),

    makePracticeQuestion("B18", 18, 4,
      "A class C network is divided into at least 6 equal-size subnets. What is the maximum number of usable hosts per subnet?",
      ["62", "32", "30", "16", "6"],
      2,
      "Six subnets require 3 borrowed bits because 2³ = 8. Five host bits remain, giving 2⁵ − 2 = 30 usable hosts."),
    makePracticeQuestion("B19", 19, 4,
      "A subnet uses the mask 255.255.255.252. What is the maximum number of usable IPv4 host addresses?",
      ["2", "4", "6", "14", "252"],
      0,
      "The /30 mask leaves 2 host bits. Four total addresses minus network and broadcast addresses leaves 2 usable hosts."),
    makePracticeQuestion("B20", 20, 4,
      "Consider a class B network with a subnet mask of 255.255.255.0. What is the maximum number of subnets?",
      ["128", "256", "512", "1024", "65,536"],
      1,
      "The /24 mask borrows 8 bits beyond the class B /16 default, producing 2⁸ = 256 subnets."),
    makePracticeQuestion("B21", 21, 4,
      "A class A network requires at least 12 subnets. How many host ID bits must be borrowed?",
      ["2", "3", "4", "12", "16"],
      2,
      "Three bits provide only 8 subnets. Four bits provide 16, so 4 is the minimum that supports at least 12 subnets."),
    makePracticeQuestion("B22", 22, 4,
      "Datagram is a common name for the PDU at which layer of the Internet Model?",
      ["Application", "Physical", "Data Link", "Network", "Transport"],
      3,
      "A network-layer packet is commonly called an IP datagram."),
    makePracticeQuestion("B23", 23, 4,
      "Which statement correctly interprets the subnet mask 255.255.240.0?",
      ["It is a /16 mask", "The same subnet is identified by the same 20 leftmost bits", "It contains 20 host bits", "It is invalid because 240 is not allowed", "The rightmost 20 bits identify the subnet"],
      1,
      "255.255.240.0 contains 20 consecutive 1-bits, making it /20. The leftmost 20 address bits identify the subnet."),
    makePracticeQuestion("B24", 24, 4,
      "A class B network must provide at least 30 subnets. What is the resulting mask when the minimum number of bits is borrowed?",
      ["255.255.248.0", "255.255.240.0", "255.255.224.0", "255.255.255.0", "255.255.30.0"],
      0,
      "Thirty subnets require 5 borrowed bits because 2⁵ = 32. Class B /16 plus 5 gives /21, or 255.255.248.0."),
    makePracticeQuestion("B25", 25, 4,
      "Which layers are generally absent from routers because they operate on end systems?",
      ["Physical and Data Link", "Data Link and Network", "Application and Transport", "Network and Physical", "Transport and Data Link"],
      2,
      "Routers need the lower three layers to move packets, while application and transport functions generally execute at the endpoints."),

    makePracticeQuestion("B26", 26, 5,
      "Which list correctly names the main layers of Structured Network Design?",
      ["Core, Session, Transport", "Access, Distribution, Core", "Client, Server, Storage", "Router, Switch, Repeater", "Physical, Wireless, Backbone"],
      1,
      "The hierarchical model organizes an enterprise network into access, distribution, and core layers."),
    makePracticeQuestion("B27", 27, 5,
      "The access layer of an organizational network normally contains...",
      ["Only carrier-owned routers", "Long-haul fibre systems", "Internet backbone exchanges", "Switches and wireless access points that connect end devices", "Only firewalls and servers"],
      3,
      "Access switches and access points provide the first network connection for workstations, phones, and other end devices."),
    makePracticeQuestion("B28", 28, 5,
      "Which network is most likely to use a shared multipoint medium?",
      ["A dedicated point-to-point fibre backbone", "A leased line between two routers", "A direct switch-to-server link", "A private cable between two offices", "A local Wi-Fi network"],
      4,
      "Wi-Fi stations share a common radio channel, which makes the WLAN a multipoint environment."),
    makePracticeQuestion("B29", 29, 5,
      "Which location is most suitable for ordinary twisted-pair Ethernet cable?",
      ["A 90-metre office access-layer run", "A transatlantic connection", "An underwater carrier route", "A 40-km building-to-building link", "A satellite downlink"],
      0,
      "Twisted-pair Ethernet is well suited to short horizontal access-layer cabling, typically up to 100 metres."),
    makePracticeQuestion("B30", 30, 5,
      "In CSMA/CD, “CD” refers to the ability to...",
      ["Change the data rate", "Detect a collision while transmitting", "Correct damaged application data", "Choose a destination address", "Create a dedicated circuit"],
      1,
      "CD means Collision Detection: a transmitting station monitors the shared medium to determine whether another transmission has collided with its own."),
  ]
};
